### ISSUE TITLE
Refactor code for in memory server

### ISSUE THREAD

**Issue by antonlin1** [antonlin1/cplusplus_programming#4]
The state of the code as of now is ok. But since I have been writing it all in isolation it might not be understandable to anyone besides me? datalayer_memory is a database abstraction and for disk server one should not have to touch any code outside of datalayer. 

However, code has been written with maintainability and readability in mind, thus it is not very effective. For example, a client message is read as a whole. The derived string is then parsed several times over in order to pick out the different parameters. This could quite easily be written more efficiently. But! I thought the project would be more easily maintained with the current solution.

**Comment by antonlin1** [comment]
Oh! Major ugly hack: in memory_server.cc the datalayer object (variable name "dl") is instantiated at line 19 as global object. How solve this in nicer way? I wanted to avoid passing the object around throughout all methods in need of it (mainly functions in protocol_functions.h). Singleton could be used, but how to solve singleton in combination with inheritance (the data layer object implements an interface as to ease transition from in memory to disk server)?

**Comment by GustavSvensson3600** [comment]
Hi!

I made a new server class (server.h/cc) more or less identical to the previous main entry class (memory_server.cc) and created a new main entry class (memory_main). Since the server accepts the abstract class DataLayer one has to pass it as an argument as a point, currently there is no destructor (because it is not needed?) in server.h.

I can not for the life of me get stoi to function, I think it has to do with me windows compiler.

Anyway, check it out and correct as you see fit, the only things that are new are in the new main method and constructor for the server.

**Comment by antonlin1** [comment]
Great job! It is beautiful :)))

**Comment by GustavSvensson3600** [comment]
So it compiles on your computer?

**Comment by antonlin1** [comment]
Ooops, did not read your whole comment. Looked at the commit and thought it looked nice, hehehe. Will see if it compiles.

**Comment by antonlin1** [comment]
It compiles for me but there seems to be an issue with the certain c++ windows compilers regarding stoi: http://www.cplusplus.com/forum/beginner/120836/

**Comment by GustavSvensson3600** [comment]
That´s good enough!
